-- Execute this once if supabase/schema.sql was already executed before the full migration.

insert into storage.buckets (id, name, public)
values ('videos', 'videos', true)
on conflict (id) do nothing;

-- Recrée les profils manquants des utilisateurs Auth existants.
insert into public.profiles (id, email, name)
select id, email, coalesce(raw_user_meta_data ->> 'name', split_part(email, '@', 1))
from auth.users
where email is not null
on conflict (id) do update set email = excluded.email;

-- Après cette migration, définissez le rôle admin de votre compte dans Table Editor > profiles.

do $$ begin
  create type public.payment_method as enum ('mobile_money', 'cash_on_delivery');
exception when duplicate_object then null;
end $$;

create table if not exists public.payment_numbers (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  label text,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists payment_method public.payment_method not null default 'cash_on_delivery';
alter table public.orders add column if not exists payment_proof text;
alter table public.payment_numbers enable row level security;
drop policy if exists payment_numbers_read_public on public.payment_numbers;
create policy payment_numbers_read_public on public.payment_numbers for select using (true);
drop policy if exists payment_numbers_manage_admin on public.payment_numbers;
create policy payment_numbers_manage_admin on public.payment_numbers for all to authenticated using (public.is_admin()) with check (public.is_admin());

create table if not exists public.video_favorites (
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);

create table if not exists public.product_views (
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (product_id, user_id)
);

alter table public.product_views enable row level security;

drop policy if exists product_views_read_owner_or_admin on public.product_views;
create policy product_views_read_owner_or_admin on public.product_views
for select to authenticated using (user_id = auth.uid() or public.is_admin());
drop policy if exists product_views_insert_owner on public.product_views;
create policy product_views_insert_owner on public.product_views
for insert to authenticated with check (user_id = auth.uid());

alter table public.video_favorites enable row level security;

create policy video_favorites_owner on public.video_favorites
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy video_storage_read_public on storage.objects
for select using (bucket_id = 'videos');

create policy video_storage_upload_authenticated on storage.objects
for insert to authenticated with check (bucket_id = 'videos');

create policy video_storage_delete_admin on storage.objects
for delete to authenticated using (bucket_id = 'videos' and public.is_admin());
