create extension if not exists "pgcrypto";

insert into storage.buckets (id, name, public)
values ('videos', 'videos', true)
on conflict (id) do nothing;

create type public.user_role as enum ('user', 'admin');
create type public.order_status as enum ('pending', 'completed', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  profile_image text,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  seller_id uuid references public.profiles(id) on delete set null,
  title text not null,
  category text not null,
  price numeric(12, 2) not null check (price >= 0),
  image text,
  description text not null default '',
  trending boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.product_views (
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (product_id, user_id)
);

create table public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.profiles(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  status public.order_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_title text not null,
  product_price numeric(12, 2) not null check (product_price >= 0),
  quantity integer not null default 1 check (quantity > 0)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  receiver_role public.user_role not null,
  text text not null check (length(trim(text)) > 0),
  is_read_by_admin boolean not null default false,
  is_read_by_user boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.videos (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete set null,
  title text not null,
  description text not null default '',
  video_url text not null,
  thumbnail_url text,
  created_at timestamptz not null default now()
);

create table public.video_views (
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);

create table public.video_likes (
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);

create table public.video_favorites (
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);

create table public.video_comments (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text not null check (length(trim(text)) > 0),
  created_at timestamptz not null default now()
);

create table public.product_collections (
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  collection text not null check (collection in ('liked', 'favorites')),
  created_at timestamptz not null default now(),
  primary key (product_id, user_id, collection)
);

create table public.carts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  updated_at timestamptz not null default now()
);

create table public.cart_items (
  cart_id uuid not null references public.carts(user_id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  primary key (cart_id, product_id)
);

create table public.user_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  language text not null default 'fr',
  site_background jsonb not null default '{"type":"default","value":""}'::jsonb,
  message_background jsonb not null default '{"type":"default","value":""}'::jsonb,
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  text text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.ad_videos (
  video_id bigint primary key references public.videos(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now()
);

create index products_category_idx on public.products(category);
create index products_trending_idx on public.products(trending) where trending = true;
create index orders_customer_idx on public.orders(customer_id);
create index orders_status_idx on public.orders(status);
create index messages_user_created_idx on public.messages(user_id, created_at);
create index videos_created_idx on public.videos(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create trigger user_settings_set_updated_at before update on public.user_settings
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_views enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.messages enable row level security;
alter table public.videos enable row level security;
alter table public.video_views enable row level security;
alter table public.video_likes enable row level security;
alter table public.video_favorites enable row level security;
alter table public.video_comments enable row level security;
alter table public.product_collections enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.user_settings enable row level security;
alter table public.notifications enable row level security;
alter table public.ad_videos enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create policy profiles_select_authenticated on public.profiles
for select to authenticated using (id = auth.uid() or public.is_admin());
create policy profiles_update_self on public.profiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy products_read_public on public.products
for select using (true);
create policy products_insert_admin on public.products
for insert to authenticated with check (public.is_admin());
create policy products_update_admin on public.products
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy products_delete_admin on public.products
for delete to authenticated using (public.is_admin());

create policy product_views_read_owner_or_admin on public.product_views
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy product_views_insert_owner on public.product_views
for insert to authenticated with check (user_id = auth.uid());

create policy orders_insert_authenticated on public.orders
for insert to authenticated with check (customer_id = auth.uid());
create policy orders_select_owner_or_admin on public.orders
for select to authenticated using (customer_id = auth.uid() or public.is_admin());
create policy orders_update_admin on public.orders
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy order_items_select_owner_or_admin on public.order_items
for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.orders where orders.id = order_items.order_id and orders.customer_id = auth.uid()
  )
);
create policy order_items_insert_owner_or_admin on public.order_items
for insert to authenticated with check (
  public.is_admin() or exists (
    select 1 from public.orders where orders.id = order_items.order_id and orders.customer_id = auth.uid()
  )
);

create policy messages_owner_or_admin on public.messages
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy messages_insert_owner_or_admin on public.messages
for insert to authenticated with check (user_id = auth.uid() or public.is_admin());
create policy messages_update_owner_or_admin on public.messages
for update to authenticated using (user_id = auth.uid() or public.is_admin());

create policy videos_read_public on public.videos
for select using (true);
create policy videos_insert_authenticated on public.videos
for insert to authenticated with check (author_id = auth.uid() or public.is_admin());
create policy videos_update_owner_or_admin on public.videos
for update to authenticated using (author_id = auth.uid() or public.is_admin());
create policy videos_delete_owner_or_admin on public.videos
for delete to authenticated using (author_id = auth.uid() or public.is_admin());

create policy video_views_owner on public.video_views
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy video_likes_owner on public.video_likes
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy video_favorites_owner on public.video_favorites
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy video_comments_read_public on public.video_comments
for select using (true);
create policy video_comments_insert_authenticated on public.video_comments
for insert to authenticated with check (user_id = auth.uid());
create policy video_comments_delete_owner_or_admin on public.video_comments
for delete to authenticated using (user_id = auth.uid() or public.is_admin());

create policy collections_owner on public.product_collections
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy carts_owner on public.carts
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy cart_items_owner on public.cart_items
for all to authenticated using (cart_id = auth.uid()) with check (cart_id = auth.uid());
create policy settings_owner on public.user_settings
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy notifications_read_authenticated on public.notifications
for select to authenticated using (true);
create policy notifications_insert_admin on public.notifications
for insert to authenticated with check (public.is_admin());
create policy ad_videos_read_public on public.ad_videos
for select using (true);
create policy ad_videos_manage_admin on public.ad_videos
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy video_storage_read_public on storage.objects
for select using (bucket_id = 'videos');
create policy video_storage_upload_authenticated on storage.objects
for insert to authenticated with check (bucket_id = 'videos');
create policy video_storage_delete_admin on storage.objects
for delete to authenticated using (bucket_id = 'videos' and public.is_admin());
